---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hcispanel/extra-miles-stage

    # Copy essential Laravel application directories to deployment path
    - /bin/cp -r app bootstrap config database routes resources $DEPLOYPATH

    - /bin/cp -r public/build $DEPLOYPATH/public

    # Copy public assets to the public_html directory
    - /bin/cp -r public/css public/img public/images public/js public/scss /home/hcispanel/public_html/extramiles-stage.hcis.live

    # Change directory to the deployment path
    - cd $DEPLOYPATH

    # Install production dependencies using Composer
    # - composer install --no-dev --optimize-autoloader

    # Run database migrations (for first deployment)
    # - php artisan migrate --force

    # Clear Laravel application cache
    - php artisan optimize:clear
    
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/hcis8257/kpn-em

#     # Copy essential Laravel application directories to deployment path
#     - /bin/cp -r app bootstrap config database routes resources $DEPLOYPATH
    
#     - /bin/cp -r public/build $DEPLOYPATH/public

#     # Copy public assets to the public_html directory
#     - /bin/cp -r public/css public/img public/images public/js public/scss /home/hcis8257/public_html/kpnem.hcis.dev

#     # Change directory to the deployment path
#     - cd $DEPLOYPATH

#     # Install production dependencies using Composer
#     # - composer install --no-dev --optimize-autoloader

#     # Run database migrations (for first deployment)
#     # - php artisan migrate --force

#     # Clear Laravel application cache
#     - php artisan optimize:clear
